[agent]
  interval = "5s"
  flush_interval = "5s"

[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]
  topics = ["jenkins/builds/events"]
  data_format = "json"
  json_time_key = "event_time"
  json_time_format = "2006-01-02T15:04:05Z"
  json_string_fields = [
    "source", "level", "message", "event_type",
    "anomaly_reason", "endpoint", "user", "raw_log",
    "mqtt_topic", "event_id", "schema_version"
  ]

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "gid-secret-token"
  organization = "tgr"
  bucket = "jenkins_events"
